/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "../JuceLibraryCode/JuceHeader.h"
#include "MainWindow.h"


//==============================================================================
class magisterkaApplication  : public JUCEApplication
{
public:
    //==============================================================================
    magisterkaApplication()
    {
    }

    ~magisterkaApplication()
    {
    }

    //==============================================================================
    void initialise (const String& commandLine)
    {
        // Do your application's initialisation code here..
        mainWindow.setVisible (true);// = new MainAppWindow();
		mainWindow.setFullScreen (true);
		
        //mainWindow.centreWithSize (700, 600);
    }

    void shutdown()
    {
        // Do your application's shutdown code here..
        //mainWindow = 0;
    }

    //==============================================================================
    void systemRequestedQuit()
    {
        quit();
    }

    //==============================================================================
    const String getApplicationName()
    {
        return "magisterka";
    }

    const String getApplicationVersion()
    {
        return ProjectInfo::versionString;
    }

    bool moreThanOneInstanceAllowed()
    {
        return true;
    }

    void anotherInstanceStarted (const String& commandLine)
    {
        
    }

private:
    MainAppWindow mainWindow;
};

//==============================================================================
// This macro generates the main() routine that starts the app.
START_JUCE_APPLICATION(magisterkaApplication)
